language: node_js
node_js:
    - "0.12"
before_install:
    - npm install -g grunt-cli
    - npm install -g bower
    - bower install
    - npm update
    - bower update
notifications:
    email:
        on_success: change
        on_failure: change
sudo: false
cache:
    directories:
        - node_modules
        - src/agrc
        - src/bootstrap
        - src/dijit
        - src/dojo
        - src/dojox
        - src/ijit
        - src/jasmine-favicon-reporter
        - src/stubmodule
        - src/util
        - src/proj4
        - src/jasmine-jsreporter
        - src/xstyle
