LOCAL_CONNECTION_STRING = 'DRIVER={SQL Server};SERVER=(local);DATABASE=WRI;Trusted_Connection=yes;'
DEV_CONNECTION_STRING = 'DRIVER={SQL Server};SERVER=;DATABASE=WRI;UID=;PWD='
AT_CONNECTION_STRING = 'DRIVER={SQL Server};SERVER=;DATABASE=;UID=;PWD='

JSONDIR = '..\\..\\src\\jsonconfig'
